import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Bot, Check, ShieldCheck, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'

import { generateRecommendation, getRecommendations, reviewRecommendation } from '../api/ai'
import { getRisks } from '../api/risks'
import type { AIRecommendation } from '../types/ai'

export function RecommendationsPage() {
  const client = useQueryClient(); const [riskId, setRiskId] = useState(''); const [editing, setEditing] = useState<AIRecommendation | null>(null)
  const risks = useQuery({ queryKey: ['risks', 'ai'], queryFn: () => getRisks() })
  const recommendations = useQuery({ queryKey: ['ai-recommendations'], queryFn: getRecommendations })
  const generate = useMutation({ mutationFn: generateRecommendation, onSuccess: () => void client.invalidateQueries({ queryKey: ['ai-recommendations'] }) })
  const review = useMutation({ mutationFn: ({ item, status }: { item: AIRecommendation; status: AIRecommendation['status'] }) => reviewRecommendation(item.id, status, item.title, item.summary, item.actions), onSuccess: () => { setEditing(null); void client.invalidateQueries({ queryKey: ['ai-recommendations'] }) } })
  return <main className="min-h-screen bg-slate-50 px-5 py-8"><section className="mx-auto max-w-5xl"><Link className="inline-flex items-center gap-2 text-sm text-blue-700" to="/panel"><ArrowLeft size={16} /> Panel</Link><div className="mt-5"><p className="text-sm font-semibold text-blue-700">Asistencia supervisada</p><h1 className="mt-1 text-3xl font-bold text-blue-950">Recomendaciones</h1><p className="mt-2 text-slate-600">Todo contenido asistido debe revisarse; ninguna acción se aplica automáticamente.</p></div>
    <section className="mt-6 rounded-xl border bg-white p-5"><h2 className="font-semibold text-blue-950">Generar borrador de tratamiento</h2><div className="mt-3 flex flex-col gap-3 sm:flex-row"><select aria-label="Riesgo" className="flex-1 rounded-lg border p-2" value={riskId} onChange={(event) => setRiskId(event.target.value)}><option value="">Seleccione un riesgo</option>{risks.data?.items.map((risk) => <option key={risk.id} value={risk.id}>{risk.code} · {risk.title}</option>)}</select><button disabled={!riskId || generate.isPending} className="rounded-lg bg-blue-950 px-4 py-2 font-semibold text-white disabled:opacity-50" onClick={() => generate.mutate(riskId)}><Bot className="mr-2 inline" size={18} />{generate.isPending ? 'Generando…' : 'Generar borrador'}</button></div>{generate.isError && <p role="alert" className="mt-3 text-red-800">No fue posible generar la recomendación.</p>}</section>
    {recommendations.isPending && <p role="status" className="mt-6">Cargando recomendaciones…</p>}{recommendations.isError && <p role="alert" className="mt-6 text-red-800">No fue posible cargar las recomendaciones.</p>}{recommendations.data?.length === 0 && <p className="mt-6 rounded-xl border border-dashed bg-white p-8 text-center">Aún no hay recomendaciones.</p>}
    <div className="mt-6 grid gap-4">{recommendations.data?.map((item) => <article key={item.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><span className="rounded-full bg-violet-100 px-2 py-1 text-xs font-semibold text-violet-900"><Bot className="mr-1 inline" size={14} />Contenido asistido {item.is_fallback ? '· modo local' : '· IA'}</span><h2 className="mt-3 text-xl font-bold text-blue-950">{item.title}</h2></div><span className="rounded-full bg-slate-100 px-2 py-1 text-sm">{item.status}</span></div><p className="mt-3">{item.summary}</p><ul className="mt-4 list-disc space-y-2 pl-5">{item.actions.map((action, index) => <li key={index}><strong>{action.action}</strong> — {action.rationale} ({action.priority})</li>)}</ul><p className="mt-4 text-sm text-slate-500">Referencias: {item.references.join(', ')} · Modelo: {item.model} · Prompt: {item.prompt_version}</p>{item.status === 'draft' && <div className="mt-4 flex flex-wrap gap-2"><button className="rounded-lg border px-3 py-2" onClick={() => setEditing(item)}>Editar y revisar</button><button className="rounded-lg bg-emerald-700 px-3 py-2 text-white" onClick={() => review.mutate({ item, status: 'approved' })}><Check className="mr-1 inline" size={16} />Aprobar</button><button className="rounded-lg bg-red-700 px-3 py-2 text-white" onClick={() => review.mutate({ item, status: 'rejected' })}><X className="mr-1 inline" size={16} />Rechazar</button></div>}</article>)}</div>
    {editing && <EditDialog item={editing} onChange={setEditing} onCancel={() => setEditing(null)} onSave={() => review.mutate({ item: editing, status: 'draft' })} />}
    <p className="mt-8 flex gap-2 rounded-lg bg-blue-50 p-4 text-sm text-blue-950"><ShieldCheck className="shrink-0" size={19} />Estas sugerencias no certifican cumplimiento ni sustituyen la decisión de una persona responsable.</p>
  </section></main>
}

function EditDialog({ item, onChange, onCancel, onSave }: { item: AIRecommendation; onChange: (item: AIRecommendation) => void; onCancel: () => void; onSave: () => void }) { return <div className="fixed inset-0 z-10 bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="edit-ai-title" className="mx-auto max-w-2xl rounded-xl bg-white p-6"><h2 id="edit-ai-title" className="text-xl font-bold">Editar recomendación</h2><label className="mt-4 block">Título<input className="mt-1 w-full rounded-lg border p-2" value={item.title} onChange={(event) => onChange({ ...item, title: event.target.value })} /></label><label className="mt-4 block">Resumen<textarea className="mt-1 min-h-32 w-full rounded-lg border p-2" value={item.summary} onChange={(event) => onChange({ ...item, summary: event.target.value })} /></label><div className="mt-5 flex justify-end gap-2"><button className="px-4 py-2" onClick={onCancel}>Cancelar</button><button className="rounded-lg bg-blue-950 px-4 py-2 text-white" onClick={onSave}>Guardar borrador</button></div></div></div> }
