import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { useState, type ReactNode } from 'react'
import { registerOrganization } from '../api/auth'
import { PasswordInput } from '../components/PasswordInput'
import { normalizeOrganizationSlug, registerSchema, type RegisterValues } from '../schemas/auth'

export function RegisterPage({ onBack }: { onBack?: () => void }) {
  const [created, setCreated] = useState(false)
  const { register, handleSubmit, setError, setValue, formState: { errors, isSubmitting } } = useForm<RegisterValues>({ resolver: zodResolver(registerSchema), defaultValues: { country: 'GT' } })
  const submit = async (values: RegisterValues) => { try { await registerOrganization(values); setCreated(true) } catch { setError('root', { message: 'No fue posible registrar la empresa. Revise que el correo y el identificador no estén en uso.' }) } }
  if (created) return <main className="px-5 py-10"><section className="mx-auto max-w-3xl rounded-2xl border bg-white p-7"><h1 className="text-2xl font-bold text-blue-950">Empresa registrada</h1><p role="status" className="mt-3">La empresa y su cuenta administradora se crearon correctamente.</p><button type="button" className="mt-5 block text-blue-700" onClick={onBack}>Volver a seleccionar empresa</button></section></main>
  return <main className="min-h-screen bg-slate-100 px-5 py-10"><section className="mx-auto max-w-3xl rounded-2xl border bg-white p-7 shadow-sm"><p className="text-sm font-semibold text-blue-700">Nueva organización</p><h1 className="mt-1 text-3xl font-bold text-blue-950">Registrar una empresa</h1><p className="mt-2 text-slate-600">Cree un espacio privado para su MIPYME. La primera cuenta será administradora.</p><form className="mt-7 grid gap-4 sm:grid-cols-2" onSubmit={handleSubmit(submit)}><Field label="Nombre completo" error={errors.full_name?.message}><input className="input" {...register('full_name')} /></Field><Field label="Correo" error={errors.email?.message}><input type="email" className="input" {...register('email')} /></Field><Field label="Contraseña" error={errors.password?.message}><PasswordInput className="input" autoComplete="new-password" {...register('password')} /></Field><Field label="Nombre de la empresa" error={errors.organization_name?.message}><input className="input" {...register('organization_name')} /></Field><Field label="Identificador de la empresa" error={errors.organization_slug?.message}><input placeholder="mi-empresa" className="input" {...register('organization_slug', { onBlur: (event) => setValue('organization_slug', normalizeOrganizationSlug(event.target.value), { shouldValidate: true }) })} /><span className="mt-1 block text-xs font-normal text-slate-600">Puede escribir “mi-empresa” o pegar su sitio web; lo convertiremos automáticamente.</span></Field><Field label="Sector"><input className="input" {...register('sector')} /></Field><Field label="Tamaño"><select className="input" {...register('size')}><option value="">Seleccionar</option><option>Microempresa</option><option>Pequeña empresa</option><option>Mediana empresa</option></select></Field><Field label="País"><input maxLength={2} className="input uppercase" {...register('country')} /></Field>{errors.root && <p role="alert" className="text-red-800 sm:col-span-2">{errors.root.message}</p>}<button disabled={isSubmitting} className="rounded-lg bg-blue-950 px-4 py-3 font-semibold text-white sm:col-span-2">{isSubmitting ? 'Creando…' : 'Crear empresa'}</button></form><button type="button" className="mt-5 block w-full text-center text-blue-700" onClick={onBack}>Volver a seleccionar empresa</button></section></main>
}
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="font-medium">{label}{children}{error && <span className="mt-1 block text-sm text-red-700">{error}</span>}</label> }
